
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    #    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/demo;DB_CLOSE_DELAY=-1
    #    hikari:
    #      pool-name: Hikari
    #      auto-commit: false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    liquibase: INFO
